# Workflow 名称
name: "Build and Push Multi-Arch Image to Aliyun"

# 环境变量
env:
  REGISTRY: registry.cn-hangzhou.aliyuncs.com
  IMAGE_NAMESPACE: testwydimage
  IMAGE_NAME: sriov-cni

# 触发条件
on:
  push:
    branches:
      - master
  workflow_dispatch:

# ===================================================================
# 推荐添加的并发控制块
# 作用：确保同一分支上只有一个实例在运行，新的推送会自动取消旧的运行
# ===================================================================
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# 定义作业
jobs:
  build-and-push:
    name: Build and Push Multi-Arch Image
    runs-on: ubuntu-22.04 # 建议使用更新的版本，如 22.04 或 ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.USERNAME_ALI }}
          password: ${{ secrets.PASSWORD_ALI }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          platforms: linux/amd64
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: ./Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: push 
        run: |
             docker login --username=891837847@qq.com registry.cn-hangzhou.aliyuncs.com -p wyd,boy1988
             docker push  ${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ env.IMAGE_NAME }}:latest
